# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.client.replicaCount }} 
  selector:
    matchLabels:
      component: client  # Selector to match Pods controlled by this Deployment
  template:
    metadata:
      labels:
        component: client  # Labels to apply to Pods created by this Deployment
    spec:
      containers:
        - name: client  # Name of the container
          image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }} 
          ports:
            - containerPort: 3000  # Port on which the container listens

---

# Service configuration
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client-clusterip  # The name of the Service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: client  # Selector to determine which Pods the Service should forward traffic to
  ports:
    - port: 3000  # Port on which the Service listens
      targetPort: 3000  # Port to forward incoming traffic to on the Pods
      protocol: TCP  
