# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
          env:
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-clusterip 
            - name: REDIS_PORT
              value: '6379'
